"""Given a bunch of optimized parameters, calculate the cost functions"""

import argparse
from itertools import combinations
import numpy as np
import time
import openfermion as of
import scipy.sparse.linalg as spla


from optimization_abc import variance_restricted, compute_spin_rdms_from_statevector

from bitstring_utils import popcount
from cost_functions import commutator_cost_number_pres

if __name__=="__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("molpath",
                        help="path to the Hamiltonian (hdf5 generated by openfermion)")
    parser.add_argument("xs",
                        help="path to file with data points (one line = one point)")
    args = parser.parse_args()

    mol = of.MolecularData(filename=args.molpath)

    basis_bitstrings = [b for b in range(2 ** (2 * mol.n_orbitals))
                        if popcount(b) == mol.n_electrons]
    basis_idx = np.array(basis_bitstrings, dtype=int)

    H_ferm = of.get_fermion_operator(
        mol.get_molecular_hamiltonian())
    H_qubit = of.jordan_wigner(H_ferm)
    H_full = of.get_sparse_operator(H_qubit, 2 * mol.n_orbitals).tocsc()

    H_sub = H_full[basis_idx, :][:, basis_idx].todense()
    evals, evecs = spla.eigsh(H_sub, k=1, which="SA")
    E_fci = float(np.real(evals[0]))
    v_sub = evecs[:, 0]

    # this one can be used in Linjun's tests for variance
    # and for creating the RDMs
    psi_full = np.zeros(2 ** (2 * mol.n_orbitals), dtype=np.complex128)
    psi_full[basis_idx] = v_sub
    psi_full /= np.linalg.norm(psi_full)

    psi_hf_sub = np.zeros_like(v_sub)
    psi_hf_sub[-1] = 1.
    psi_hf_full = np.zeros(2 ** (2 * mol.n_orbitals), dtype=np.complex128)
    psi_hf_full[basis_idx] = psi_hf_sub

    rdms_fci = compute_spin_rdms_from_statevector(psi_full, mol.n_orbitals)
    rdms_hf = compute_spin_rdms_from_statevector(psi_hf_full, mol.n_orbitals)

    pairs = list(combinations(range(mol.n_orbitals), 2))
    variance_fci = lambda x: variance_restricted(
        rdms_fci[0], rdms_fci[1], rdms_fci[2], x, pairs
    )[0]

    variance_hf = lambda x: variance_restricted(
        rdms_hf[0], rdms_hf[1], rdms_hf[2], x, pairs
    )[0]

    # this one can be used in my stuff
    # idk why I have two representations of the same thing but that's what I have
    H_number = of.get_number_preserving_sparse_operator(
        H_ferm, num_electrons=mol.n_electrons,
        num_qubits=mol.n_orbitals * 2
    ).todense()

    _, psi_fci_number = spla.eigsh(H_number, which="SA", k=1)

    commutator_fci, _ = commutator_cost_number_pres(H_number,
                                       psi_fci_number,
                                       mol.n_electrons,
                                       mol.n_orbitals)

    psi_hf = np.zeros(H_number.shape[0])
    psi_hf[0] = 1.
    commutator_hf, _ = commutator_cost_number_pres(H_number,
                                                    psi_hf,
                                                    mol.n_electrons,
                                                    mol.n_orbitals)

    xs = np.loadtxt(args.xs, skiprows=1)

    n_points = xs.shape[0]

    data_filename = args.xs + "_results.txt"
    fieldnames = ["V_fci", "V_hf", "C_fci", "C_hf", "b", "c"]

    with open(data_filename,
              "a", newline="") as fp:
        fp.write(" ".join(fieldnames) + "\n")

    for i in range(n_points):
        x = xs[i, :]
        phi1, phi2 = x[-2], x[-1]
        a_opt = np.sin(phi1) * np.cos(phi2)
        b_opt = np.sin(phi1) * np.sin(phi2)
        c_opt = np.cos(phi1)
        costs_and_bc = np.array([variance_fci(x), variance_hf(x),
                        commutator_fci(x), commutator_hf(x), b_opt / a_opt, c_opt / a_opt])
        print(costs_and_bc)

        with open(data_filename, "ab") as fp:
            np.savetxt(fp, costs_and_bc.reshape(1, costs_and_bc.shape[0]))